import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#fff' },
  flex: { flex: 1 },
  form: { marginTop: 32, paddingHorizontal: 24 },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 8,
    paddingTop: 18,
  },
  closeBtn: { fontSize: 34, color: '#1976d2', marginRight: 6, marginTop: -5 },
  header: {
    fontSize: 28,
    fontWeight: 'bold',
    marginLeft: 4,
    flex: 1,
    color: '#222',
  },
  input: {
    height: 46,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    marginBottom: 24,
    fontSize: 18,
    color: '#333',
    paddingHorizontal: 0,
    backgroundColor: '#fff',
  },
  label: {
    fontSize: 18,
    color: '#333',
    marginBottom: 12,
    fontWeight: '500',
  },
  roleSwitch: {
    flexDirection: 'row',
    backgroundColor: '#f7fafd',
    borderRadius: 30,
    marginBottom: 16,
    borderWidth: 0,
    alignItems: 'center',
    height: 54,
  },
  roleBtn: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 30,
    marginHorizontal: 2,
    backgroundColor: 'transparent',
  },
  roleBtnSelected: {
    backgroundColor: '#e8f1fe',
    borderColor: '#1a73e8',
    borderWidth: 1.5,
  },
  roleText: {
    fontSize: 18,
    color: '#9ba6b2',
    fontWeight: '500',
  },
  roleTextSelected: {
    color: '#1a73e8',
    fontWeight: '700',
  },
  createBtn: {
    marginTop: 'auto',
    backgroundColor: '#0176d3',
    marginHorizontal: 16,
    marginBottom: 18,
    borderRadius: 30,
    height: 56,
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: "#1976d2",
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 8,
    elevation: 2,
  },
  createBtnText: {
    color: '#fff',
    fontSize: 20,
    fontWeight: '600',
    letterSpacing: 0.6,
  },
  error: {
    color: '#f44336',
    marginTop: 2,
    marginBottom: 6,
    fontSize: 16,
    textAlign: 'center',
  },
});